# Generated by Django 4.1.3 on 2023-03-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogservice', '0002_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('text', models.TextField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
